---
title: "ICU_hackathon"
author: "Jeremy Lewis"
date: "10/4/2019"
output: html_document
---



```{r}
#install.packages("ggplot2")
#install.packages("shiny")
#install.packages("shinydashboard")

library(ggplot2)
library(shiny)
library(shiny)
library(tidyverse)
```




```{r}

```


```{r}
### Pretend that dipl is our model weights

#range(mpg$displ)

# Make dummy variables that are equal to disp (our pretend weights) times out pretend model variables:
## w_<variable> denotes the weighted data of our <variable> 

mpg$w_cyl <- mpg$displ*mpg$cyl
mpg$w_hwy <- mpg$displ*mpg$hwy
mpg$w_cyl <- mpg$displ*mpg$cyl
mpg$w_cyl <- mpg$displ*mpg$cyl
mpg$w_cyl <- mpg$displ*mpg$cyl
mpg$w_cyl <- mpg$displ*mpg$cyl
mpg$w_cyl <- mpg$displ*mpg$cyl
mpg$w_cyl <- mpg$displ*mpg$cyl
mpg$w_cyl <- mpg$displ*mpg$cyl


```

### Fake data:

```{r}
  #fake_weights <-  runif(5, -2, 7.5)

  weight <- c("unweighted", "weighted")
 
  v1 <-  runif(1, 10, 20)
  v1 <- c(v1, v1*1.8)  
  
  v2 <-  runif(1, 20, 30)
  v2 <- c(v2, v2*1.2)
  
  v3 <-  runif(1, 50, 60)
  v3 <- c(v3, v3*(-1))
  
  v4 <-  runif(1, 17, 19)
  v4 <- c(v4, v4*1.7)
  
  v5 <-  runif(1, 50, 70)
  v5 <- c(v5, v5*1.6)
```
  
```{r}
df <- data.frame(v1, v2, v3, v4, v5, weight)


df <- gather(df, variable, value, 1:5)

head(df)
```




```{r}
p <- ggplot(data = df, aes(fill = weight, x= variable , y= value)) +
  geom_bar(position = "dodge", stat="identity", alpha = 1, width = .75) +
  ggtitle("Mock Plot") +
 # scale_y_continuous(limits = c(0, 72), breaks = seq(0, 70, 10)) +
  labs(x = "Variable", y = "Value") +
  theme(panel.background = element_blank(), 
        axis.line.x = element_line(colour = "grey40", size = .2), 
        axis.line.y = element_line(colour = "grey40", size = .2)) 
 # scale_fill_manual(name = "Achievement Level", values = c("orchid2", "plum1", "skyblue1", "royalblue1" ))

p

```



```{r}
## We can compare the apache score to some comparitor like the mean appache score
##  For example, here I set the comparison value to 28
comparison <- 40

### Plot a single bar representing the apache score:

df_apache <- data.frame(Apache = c("apache"), Value = c(55))

p2 <- ggplot(data = df_apache, aes(y = Value, x = Apache)) + 
  geom_hline(yintercept = comparison, linetype = 2, color = "red") +
  geom_bar(stat = "identity", width = .2, alpha = .9) + 
  scale_y_continuous(limits = c(0, 75), expand = c(0, 0)) +
  theme(panel.background = element_blank(), 
        axis.line.x = element_line(colour = "grey40", size = .2), 
        axis.line.y = element_line(colour = "grey40", size = .2),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) 


p2

```



```{r}
# Fake weighted values (weight times value), representing the contribution of variables to the apache score
## note: this will only apply to numeric variables, and categorical vars will need to be displayed differently

df2 <- data.frame("v1" = 22, "v2" = 23, "v4" = 8, "v5" = 12, "v6" = 13, "v7" = 6, "v8" = 14, "v9" = 4, 'v10' = 2, "v11" = 18, "v13"= 7, "v14" = 3, "v15" = 1, "v16" = 13, "v17" = 8, "v19" = 2, "v20" = 9, "v21" = 2, "v22"= 6, "v23" = 8, "v24" = 10, "v25" = 13)

df2 <- gather(df2, "Variable", "Weighted_Value")

# Normalize so that the weighted vairables add to less than 1 (a "possible"" probability)
df2$Weighted_Value <- (df2$Weighted_Value)/sum(df2$Weighted_Value) -.002

# Add a dummy variable to use as an x location for the bar. This variable has no real meaning, but is needed because geom_bar excpects multiple bars, but we are plotting only one
df2$dummy <- "dummy"

head(df2)

```


```{r}
#install.packages("RColorBrewer").
library(RColorBrewer)

p_stacked <- ggplot(data = df2, aes(x= dummy, y = Weighted_Value, fill = Variable)) + 
  geom_bar(position = "stack", stat = 'identity', width = .3) + 
  theme(panel.background = element_blank(), 
        axis.line.x = element_blank(), 
        axis.line.y = element_line(colour = "grey40", size = .2),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.x = element_blank(),
        legend.position = "right") +
  scale_y_continuous(expand = c(0, 0)) +
  labs(y = "Contribution to Predicted 48h Mortality") + 
  scale_fill_manual(values= c("#1B9E77", "#D95F02", "#7570B3", "#E7298A", "#66A61E", "#E6AB02", "#A6761D", "#666666", "cadetblue3", "darkslateblue", 'deeppink2', "chocolate3", "chartreuse4", "lightgoldenrod3", "pink2", "tomato3", "darkorchid3", "blue4", "coral4", "slategrey", "aquamarine2", "yellow3", "firebrick3", "lightgreen", "goldenrod4", "olivedrab1"))  

#legend.key.size = unit(.2, "cm")
#guide_legend(ncol = 1)


p_stacked
  

```

```{r}
## feature and importance score (futher from 0 means more important)
### Scores for patietn: 002-34851

df_import <- data.frame("age" = c(0.3), "ethnicity" = c(0.0), 'apacheadmissiondx' = c(-0.4), 'admissionheight' = c(-0.1), 'admissionweight' = c(-0.1), 'unitadmitsource' = c(-0.0), 'intubated' = c(-0.0), 'vent' = c(-0.1), 'dialysis' = c(-0.0), 'eyes' = c(-0.1), 'motor' = c(-0.1), 'meds'= c(0.0), 'urine' = c(0.2), 'wbc'= c(0.1), 'temperature' = c(0.1), 'respiratoryrate' = 0.1, 'sodium' = -0.1, 'heartrate' = 0.6, 'meanbp'= -0.1, 'ph'= 0.0, 'hematocrit' =  -0.0, 'albumin'= -0.3, 'pao2'= -0.0, 'pco2'= 0.0, 'bun'= 0.1, 'glucose'= -0.1, 'bilirubin' = 1.0, 'fio2'=-0.1)

df_import <- gather(df_import, "Variable", "Importance_Score")

df_import$dummy <- "dummy"


p_stacked2 <- ggplot(data = subset(df_import, df_import$Importance_Score >0), aes(x= dummy, y = Importance_Score, fill = Variable)) + 
  geom_bar(position = "stack", stat = 'identity', width = .3) + 
  theme(panel.background = element_blank(), 
        axis.line.x = element_blank(), 
        axis.text.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.x = element_blank(),
        axis.line.y = element_blank(), 
        axis.ticks.y=element_blank(),
        legend.position = "right") +
  scale_y_continuous(expand = c(0, 0)) +
  labs(y = "Importance Score for 48 Hour Mortality") + 
  scale_fill_manual(values= c("#1B9E77", "#D95F02", "#7570B3", "#E7298A", "#66A61E", "#E6AB02", "#A6761D", "#666666", "cadetblue3", "darkslateblue", 'deeppink2', "chocolate3", "chartreuse4", "lightgoldenrod3", "pink2", "tomato3", "darkorchid3", "blue4", "coral4", "slategrey", "aquamarine2", "yellow3", "firebrick3", "lightgreen", "goldenrod4", "olivedrab1", "red", "blue", "green"))  


pdf("Importance_Scores.pdf")
p_stacked2
dev.off()



```


```{r}
library(readr)
df_ICU <- read_csv("~/Desktop/health_analytics/Health_Hackathon/ICU2_UI-master/ICU_dataset.csv")
```

### Density plot for a given vairable, with our patients value marked with a vertical line:
```{r}

#df_ICU[,c(30:51)]df_ICU[,c(30:51)==-1]=NA
#head(mpg)

### Density plot for a given vairable, with our patients value marked with a vertical line:

# Identify the person 
person = 141168

# Name variable to visualize
variable <- "glucose"

# Name dataframe to input
df3 <- df_ICU


# Variable holding our patients particular score on that variable. Here, suppose we are visualizing the results for person ... :
p <- df_ICU[df_ICU$patientunitstayid==person,variable][[1]]
p


p_density <- ggplot(df3, aes(x= df3[[variable]])) + 
  geom_density(alpha=0.25, fill = "blue", alpha = .5) + 
  geom_vline(xintercept = mean(df3[[variable]]), linetype = 2, color = "black") + # vertical line for mean of feature 
   geom_vline(xintercept = p , linetype = 2, color = "red") + # vertical line showing our patient's score on this feature 
xlab(variable) +
  ggtitle(paste("Density Plot of ", variable, sep = "")) 

#+scale_color_manual(name = "Lines", values = c(mean = "black", patient = "red"))

pdf("Density_For_ParticularPatient_ParticularVaraible_Glucose.pdf")
p_density
dev.off()
  

```



